language: generic

services:
  - docker

before_install:
  - echo "Building Docker image"
  - docker build -t xintaro/docker-react -f Dockerfile.dev .

script:
  - echo "Running tests"
  - docker run -e CI=true xintaro/docker-react npm run test
